kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  nginx.conf: |
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    events {
      worker_connections 1024;
    }
    http {
      sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        error_log /var/log/nginx/error.log;
        gzip on;
        gzip_disable "msie6";
        include /etc/nginx/conf.d/testkube.dbd.net.conf;
        include /etc/nginx/snippets/*.conf;

    testkube.dbd.net: |
      upstream app {
      server example1.com www.example1.com;
      keepalive 15;
    }
      server {
        listen 80;
        listen [::]:80;

        location / {
          proxy_pass http://testkube.dbd.net;
          proxy_http_version 1.1;
          proxy_set_header Connection "Keep-Alive";
          proxy_set_header Proxy-Connection "Keep-Alive";
          proxy_redirect off;
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
