apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |-
    file_uploads = On
    memory_limit = 64M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 600
